FROM python:alpine3.21

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

COPY ../.env ./

EXPOSE 90

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "90", "--reload"]