services:
  db:
    image: postgres:17.5-alpine3.22
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_app
    restart: always
    ports:
      - "90:90"
    networks:
      - app_network
    

volumes:
  db_data:

networks:
  app_network:
